<?php

namespace TimurFlush\Queue\Tests;

use PHPUnit\Framework\TestCase;
use TimurFlush\Queue\Message;
use TimurFlush\Queue\Tests\Jobs\TestJob;

class JobLogicalTest extends TestCase
{
    /**
     * @var \TimurFlush\Queue\Job
     */
    protected $job;

    public function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->job = new TestJob();
    }

    public function testIsExceededAttempts()
    {
        $job = $this->job;

        $attempts = rand(111, 999);
        $attemptsToDelete = rand(111, 999);
        $job->setMaxAttemptsToDelete($attemptsToDelete);

        for ($i=0; $i < $attempts; $i++) {
            $job->incrementAttempt();
        }

        $this->assertEquals(($attemptsToDelete < $attempts), ($job->isExceededAttempts()), 'isExceededAttempts() is not working.');
    }

    public function testValidationHasFailed()
    {
        $job = $this->job;

        $this->assertFalse($job->validationHasFailed(), 'validationHasFailed() is not working.');

        $job->appendMessage(new Message('someText'));
        $this->assertTrue($job->validationHasFailed(), 'validationHasFailed() is not working.');
    }

    public function tearDown()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        unset($this->job);
    }
}
